### ISSUE TITLE
WCT IE11 and Edge tests are disabled

### ISSUE THREAD

**Issue by AllanKerr** [BrightspaceHypermediaComponents/users#26]
## Issue
- The IE11 and Edge WCT tests have been temporarily disabled due to a defect with WCT causing flake.
## Fix
- The fix for WCT has been merged but not released until 3.1.5:
    - https://github.com/Polymer/tools/pull/727#issuecomment-522711237
    - https://github.com/Polymer/tools/blob/master/packages/build/CHANGELOG.md#change-log
- Once this change is released then these WCT tests should be re-enabled by merging the following PR: https://github.com/BrightspaceHypermediaComponents/users/pull/25

**Comment by svanherk** [comment]
This is no longer an issue.  We use `web-test-runner` and don't test IE11 or legacy Edge.
